import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden h-full`} >
       <nav className="fixed top-0 left-0 right-0 h-14 bg-white border-b border-gray-200 z-50 flex items-center px-4">
        <div className="w-72 flex-shrink-0">
          <span className="text-lg font-semibold text-gray-900">Agent Explorer</span>
        </div>
        {/* Left side */}
        <div className="flex items-center gap-6 flex-1">
          <a href="#" className="text-sm font-medium text-gray-700 hover:text-black transition">Data Exploration</a>
          <a href="#" className="text-sm font-medium text-gray-700 hover:text-black transition">Data Catalog</a>
          <a href="#" className="text-sm font-medium text-gray-700 hover:text-black transition">Detections</a>
          <a href="#" className="text-sm font-medium text-gray-700 hover:text-black transition">Dashboards</a>
        </div>

        {/* Right side */}
        <div className="flex items-center ml-auto">
          <div className="w-8 h-8 rounded-full bg-gray-800 flex items-center justify-center text-white text-sm font-medium cursor-pointer hover:bg-gray-700 transition">
            U
          </div>
        </div>
      </nav>

        <main className="mt-14 bg-[#f7f7f8] min-h-[calc(100vh-3.5rem)]">
          {children}
        </main>
      </body>
    </html>
  );
}
